### ISSUE TITLE
Problem with [applications_to_sync]

### ISSUE THREAD

**Issue by nkgm** [lra/mackup#622]
All these programs are already installed and I'm trying to backup their settings with `mackup backup`. Unfortunately mackup will only backup **one** program from this list every time. In this example, it will only backup `bettertouchtool`, and nothing else. If I was to delete `bettertouchtool` from the list, it would backup up `karabiner`, and so on.

~/.mackup.cfg
```
[storage]
engine = dropbox
directory = nkgm-mackup

[applications_to_sync]
seil
karabiner
hammerspoon
iterm2
bettertouchtool
xtrafinder
dash
xcode
vlc
popcorn-time
spotify
intellijidea-14
```

Using mackup 0.8.9

**Comment by lra** [comment]
Strange that you don't get any error, it must be failing on one of the apps.
I just released 0.8.10 on pip with verbose and dry run.

Can you try the verbose mode using 0.8.10?

**Comment by nkgm** [comment]
Using 0.8.10 now.

I must have done something really nasty while experimenting (like renaming the `~/Dropbox/Mackup` folder after a "backup everything" run), so it was due to orphaned symlinks. I've reproduced the condition, and running with `verbose` is very informative, yet it reports orphaned symlinks as `does not exist`. I know it's an edge case, but a more detailed message would be useful if you ever get yourself into this type of situation.

**Comment by lra** [comment]
Do you have a suggestion for a better error message?

**Comment by nkgm** [comment]
I'm still getting to know mackup, so I'm not sure what would make better sense in that situation. I can tell you it was definitely confusing to a newcomer such as myself, but once you get the gist of mackup you shouldn't hit that condition. Maybe something neutral such as `does not exist (broken symlink)`, possibly implying `mackup backup` or `mackup restore` has already run and something bad happened to your dropbox files. On the other hand, I understand there's a variety of external factors at play here, so maybe we should leave it as it is, but I'll leave that decision to you.

**Comment by lra** [comment]
https://github.com/lra/mackup/commit/189335f8420346eab4323ae829eab38577e672c9
